
  access_key: 3a47c592e37e3a7537f5
  secret_key: beabadc00efbe7c2e8a5
  cloud_id:  13ad5786b30a67a0ce73a6219180fd22
  # Uncomment the line below if your account is in the EU
  # api_host: api-eu.pandastream.com
