require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BidcartsController do

  # This should return the minimal set of attributes required to create a valid
  # Bidcart. As you add validations to Bidcart, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all bidcarts as @bidcarts" do
      bidcart = Bidcart.create! valid_attributes
      get :index
      assigns(:bidcarts).should eq([bidcart])
    end
  end

  describe "GET show" do
    it "assigns the requested bidcart as @bidcart" do
      bidcart = Bidcart.create! valid_attributes
      get :show, :id => bidcart.id
      assigns(:bidcart).should eq(bidcart)
    end
  end

  describe "GET new" do
    it "assigns a new bidcart as @bidcart" do
      get :new
      assigns(:bidcart).should be_a_new(Bidcart)
    end
  end

  describe "GET edit" do
    it "assigns the requested bidcart as @bidcart" do
      bidcart = Bidcart.create! valid_attributes
      get :edit, :id => bidcart.id
      assigns(:bidcart).should eq(bidcart)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bidcart" do
        expect {
          post :create, :bidcart => valid_attributes
        }.to change(Bidcart, :count).by(1)
      end

      it "assigns a newly created bidcart as @bidcart" do
        post :create, :bidcart => valid_attributes
        assigns(:bidcart).should be_a(Bidcart)
        assigns(:bidcart).should be_persisted
      end

      it "redirects to the created bidcart" do
        post :create, :bidcart => valid_attributes
        response.should redirect_to(Bidcart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bidcart as @bidcart" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bidcart.any_instance.stub(:save).and_return(false)
        post :create, :bidcart => {}
        assigns(:bidcart).should be_a_new(Bidcart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bidcart.any_instance.stub(:save).and_return(false)
        post :create, :bidcart => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bidcart" do
        bidcart = Bidcart.create! valid_attributes
        # Assuming there are no other bidcarts in the database, this
        # specifies that the Bidcart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bidcart.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bidcart.id, :bidcart => {'these' => 'params'}
      end

      it "assigns the requested bidcart as @bidcart" do
        bidcart = Bidcart.create! valid_attributes
        put :update, :id => bidcart.id, :bidcart => valid_attributes
        assigns(:bidcart).should eq(bidcart)
      end

      it "redirects to the bidcart" do
        bidcart = Bidcart.create! valid_attributes
        put :update, :id => bidcart.id, :bidcart => valid_attributes
        response.should redirect_to(bidcart)
      end
    end

    describe "with invalid params" do
      it "assigns the bidcart as @bidcart" do
        bidcart = Bidcart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bidcart.any_instance.stub(:save).and_return(false)
        put :update, :id => bidcart.id, :bidcart => {}
        assigns(:bidcart).should eq(bidcart)
      end

      it "re-renders the 'edit' template" do
        bidcart = Bidcart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bidcart.any_instance.stub(:save).and_return(false)
        put :update, :id => bidcart.id, :bidcart => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bidcart" do
      bidcart = Bidcart.create! valid_attributes
      expect {
        delete :destroy, :id => bidcart.id
      }.to change(Bidcart, :count).by(-1)
    end

    it "redirects to the bidcarts list" do
      bidcart = Bidcart.create! valid_attributes
      delete :destroy, :id => bidcart.id
      response.should redirect_to(bidcarts_url)
    end
  end

end
