require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BiddingsController do

  # This should return the minimal set of attributes required to create a valid
  # Bidding. As you add validations to Bidding, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all biddings as @biddings" do
      bidding = Bidding.create! valid_attributes
      get :index
      assigns(:biddings).should eq([bidding])
    end
  end

  describe "GET show" do
    it "assigns the requested bidding as @bidding" do
      bidding = Bidding.create! valid_attributes
      get :show, :id => bidding.id
      assigns(:bidding).should eq(bidding)
    end
  end

  describe "GET new" do
    it "assigns a new bidding as @bidding" do
      get :new
      assigns(:bidding).should be_a_new(Bidding)
    end
  end

  describe "GET edit" do
    it "assigns the requested bidding as @bidding" do
      bidding = Bidding.create! valid_attributes
      get :edit, :id => bidding.id
      assigns(:bidding).should eq(bidding)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bidding" do
        expect {
          post :create, :bidding => valid_attributes
        }.to change(Bidding, :count).by(1)
      end

      it "assigns a newly created bidding as @bidding" do
        post :create, :bidding => valid_attributes
        assigns(:bidding).should be_a(Bidding)
        assigns(:bidding).should be_persisted
      end

      it "redirects to the created bidding" do
        post :create, :bidding => valid_attributes
        response.should redirect_to(Bidding.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bidding as @bidding" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bidding.any_instance.stub(:save).and_return(false)
        post :create, :bidding => {}
        assigns(:bidding).should be_a_new(Bidding)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bidding.any_instance.stub(:save).and_return(false)
        post :create, :bidding => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bidding" do
        bidding = Bidding.create! valid_attributes
        # Assuming there are no other biddings in the database, this
        # specifies that the Bidding created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bidding.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bidding.id, :bidding => {'these' => 'params'}
      end

      it "assigns the requested bidding as @bidding" do
        bidding = Bidding.create! valid_attributes
        put :update, :id => bidding.id, :bidding => valid_attributes
        assigns(:bidding).should eq(bidding)
      end

      it "redirects to the bidding" do
        bidding = Bidding.create! valid_attributes
        put :update, :id => bidding.id, :bidding => valid_attributes
        response.should redirect_to(bidding)
      end
    end

    describe "with invalid params" do
      it "assigns the bidding as @bidding" do
        bidding = Bidding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bidding.any_instance.stub(:save).and_return(false)
        put :update, :id => bidding.id, :bidding => {}
        assigns(:bidding).should eq(bidding)
      end

      it "re-renders the 'edit' template" do
        bidding = Bidding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bidding.any_instance.stub(:save).and_return(false)
        put :update, :id => bidding.id, :bidding => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bidding" do
      bidding = Bidding.create! valid_attributes
      expect {
        delete :destroy, :id => bidding.id
      }.to change(Bidding, :count).by(-1)
    end

    it "redirects to the biddings list" do
      bidding = Bidding.create! valid_attributes
      delete :destroy, :id => bidding.id
      response.should redirect_to(biddings_url)
    end
  end

end
