require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LineBidsController do

  # This should return the minimal set of attributes required to create a valid
  # LineBid. As you add validations to LineBid, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all line_bids as @line_bids" do
      line_bid = LineBid.create! valid_attributes
      get :index
      assigns(:line_bids).should eq([line_bid])
    end
  end

  describe "GET show" do
    it "assigns the requested line_bid as @line_bid" do
      line_bid = LineBid.create! valid_attributes
      get :show, :id => line_bid.id
      assigns(:line_bid).should eq(line_bid)
    end
  end

  describe "GET new" do
    it "assigns a new line_bid as @line_bid" do
      get :new
      assigns(:line_bid).should be_a_new(LineBid)
    end
  end

  describe "GET edit" do
    it "assigns the requested line_bid as @line_bid" do
      line_bid = LineBid.create! valid_attributes
      get :edit, :id => line_bid.id
      assigns(:line_bid).should eq(line_bid)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LineBid" do
        expect {
          post :create, :line_bid => valid_attributes
        }.to change(LineBid, :count).by(1)
      end

      it "assigns a newly created line_bid as @line_bid" do
        post :create, :line_bid => valid_attributes
        assigns(:line_bid).should be_a(LineBid)
        assigns(:line_bid).should be_persisted
      end

      it "redirects to the created line_bid" do
        post :create, :line_bid => valid_attributes
        response.should redirect_to(LineBid.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved line_bid as @line_bid" do
        # Trigger the behavior that occurs when invalid params are submitted
        LineBid.any_instance.stub(:save).and_return(false)
        post :create, :line_bid => {}
        assigns(:line_bid).should be_a_new(LineBid)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LineBid.any_instance.stub(:save).and_return(false)
        post :create, :line_bid => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested line_bid" do
        line_bid = LineBid.create! valid_attributes
        # Assuming there are no other line_bids in the database, this
        # specifies that the LineBid created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LineBid.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => line_bid.id, :line_bid => {'these' => 'params'}
      end

      it "assigns the requested line_bid as @line_bid" do
        line_bid = LineBid.create! valid_attributes
        put :update, :id => line_bid.id, :line_bid => valid_attributes
        assigns(:line_bid).should eq(line_bid)
      end

      it "redirects to the line_bid" do
        line_bid = LineBid.create! valid_attributes
        put :update, :id => line_bid.id, :line_bid => valid_attributes
        response.should redirect_to(line_bid)
      end
    end

    describe "with invalid params" do
      it "assigns the line_bid as @line_bid" do
        line_bid = LineBid.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LineBid.any_instance.stub(:save).and_return(false)
        put :update, :id => line_bid.id, :line_bid => {}
        assigns(:line_bid).should eq(line_bid)
      end

      it "re-renders the 'edit' template" do
        line_bid = LineBid.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LineBid.any_instance.stub(:save).and_return(false)
        put :update, :id => line_bid.id, :line_bid => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested line_bid" do
      line_bid = LineBid.create! valid_attributes
      expect {
        delete :destroy, :id => line_bid.id
      }.to change(LineBid, :count).by(-1)
    end

    it "redirects to the line_bids list" do
      line_bid = LineBid.create! valid_attributes
      delete :destroy, :id => line_bid.id
      response.should redirect_to(line_bids_url)
    end
  end

end
