require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaymentNotificationsController do

  # This should return the minimal set of attributes required to create a valid
  # PaymentNotification. As you add validations to PaymentNotification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all payment_notifications as @payment_notifications" do
      payment_notification = PaymentNotification.create! valid_attributes
      get :index
      assigns(:payment_notifications).should eq([payment_notification])
    end
  end

  describe "GET show" do
    it "assigns the requested payment_notification as @payment_notification" do
      payment_notification = PaymentNotification.create! valid_attributes
      get :show, :id => payment_notification.id
      assigns(:payment_notification).should eq(payment_notification)
    end
  end

  describe "GET new" do
    it "assigns a new payment_notification as @payment_notification" do
      get :new
      assigns(:payment_notification).should be_a_new(PaymentNotification)
    end
  end

  describe "GET edit" do
    it "assigns the requested payment_notification as @payment_notification" do
      payment_notification = PaymentNotification.create! valid_attributes
      get :edit, :id => payment_notification.id
      assigns(:payment_notification).should eq(payment_notification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PaymentNotification" do
        expect {
          post :create, :payment_notification => valid_attributes
        }.to change(PaymentNotification, :count).by(1)
      end

      it "assigns a newly created payment_notification as @payment_notification" do
        post :create, :payment_notification => valid_attributes
        assigns(:payment_notification).should be_a(PaymentNotification)
        assigns(:payment_notification).should be_persisted
      end

      it "redirects to the created payment_notification" do
        post :create, :payment_notification => valid_attributes
        response.should redirect_to(PaymentNotification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved payment_notification as @payment_notification" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotification.any_instance.stub(:save).and_return(false)
        post :create, :payment_notification => {}
        assigns(:payment_notification).should be_a_new(PaymentNotification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotification.any_instance.stub(:save).and_return(false)
        post :create, :payment_notification => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested payment_notification" do
        payment_notification = PaymentNotification.create! valid_attributes
        # Assuming there are no other payment_notifications in the database, this
        # specifies that the PaymentNotification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PaymentNotification.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => payment_notification.id, :payment_notification => {'these' => 'params'}
      end

      it "assigns the requested payment_notification as @payment_notification" do
        payment_notification = PaymentNotification.create! valid_attributes
        put :update, :id => payment_notification.id, :payment_notification => valid_attributes
        assigns(:payment_notification).should eq(payment_notification)
      end

      it "redirects to the payment_notification" do
        payment_notification = PaymentNotification.create! valid_attributes
        put :update, :id => payment_notification.id, :payment_notification => valid_attributes
        response.should redirect_to(payment_notification)
      end
    end

    describe "with invalid params" do
      it "assigns the payment_notification as @payment_notification" do
        payment_notification = PaymentNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotification.any_instance.stub(:save).and_return(false)
        put :update, :id => payment_notification.id, :payment_notification => {}
        assigns(:payment_notification).should eq(payment_notification)
      end

      it "re-renders the 'edit' template" do
        payment_notification = PaymentNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PaymentNotification.any_instance.stub(:save).and_return(false)
        put :update, :id => payment_notification.id, :payment_notification => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested payment_notification" do
      payment_notification = PaymentNotification.create! valid_attributes
      expect {
        delete :destroy, :id => payment_notification.id
      }.to change(PaymentNotification, :count).by(-1)
    end

    it "redirects to the payment_notifications list" do
      payment_notification = PaymentNotification.create! valid_attributes
      delete :destroy, :id => payment_notification.id
      response.should redirect_to(payment_notifications_url)
    end
  end

end
